[package]
name = "actix-shs-cli"
version = "0.1.0"
authors = ["Qian Linfeng <thewawar@gmail.com>"]

[dependencies]
serde_json = "1.0"
askama = "0.7"
pretty-bytes = "0.2"
url = "1.7"
chrono = "0.4"
clap = "2.32"
actix-web = "0.7"
actix-shs = { path = "../actix-shs", version = "0.1.0" }
