[package]
name = "actix-shs-cli"
version = "0.1.0"
authors = ["Qian Linfeng <thewawar@gmail.com>"]

[dependencies]
serde_json = "^1.0.21"
tera = "^0.11.7"
clap = "^2.31.2"
actix-web = "^0.6.13"
actix-shs = { path = "../actix-shs", version = "0.1.0" }
